//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theoretical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemEntity
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public decimal SalePrice { get; set; }
        public string Upc { get; set; }
        public bool HasSerialNumber { get; set; }
        public string SerialNumber { get; set; }
        public int ConcurrencyId { get; set; }
    
        public virtual OrderEntity Order { get; set; }
    }
}
