//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theoretical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiKeyEntity
    {
        public int KeyOne { get; set; }
        public System.Guid KeyTwo { get; set; }
        public string KeyThree { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public int ConcurrencyId { get; set; }
        public int OrderId { get; set; }
    
        public virtual OrderEntity Order { get; set; }
    }
}
