//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theoretical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string VendorName { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public decimal SalePrice { get; set; }
        public bool IsDiscontinued { get; set; }
        public bool IsSerialNumberRequired { get; set; }
        public int ConcurrencyId { get; set; }
    }
}
